# -*- coding: utf-8 -*-
"""hello_World_Program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAuX9KgnxZuvHwIOPTM9vwc5MQKcrLrc
"""

print("Hello, World!")

FIRSTname = "SARAH"  #User first name
MIDDLEname = "AFRAH"  #User middle name
LASTname = "OBENG"  #User last name

print(f"Hello {FIRSTname}")

print(f"{MIDDLEname} World!")

print(f"{LASTname} World!")
